#!/bin/sh
# Update UFO after editing with FontForge and prior to commit

# Stop on any errors
set -e

# Check and normalize all UFOs first -- assumes no other steps de-normalize
echo "Fixing FontForge debris and normalizing UFOs..."
psffixffglifs -p checkfix=fix source/*-Regular.ufo  &
psffixffglifs -p checkfix=fix source/*-Light.ufo    &
wait

echo "Updating glyph orders in Regular..."
psfsetglyphorder -q -p checkfix=none -p backup=False --header sort_final,sort_designer --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/*-Regular.ufo

echo "Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -p backup=False -i source/glyph_data.csv source/*-Regular.ufo

echo "Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/*.designspace

echo "Updating woff metadata file..."
psfmakewoffmetadata -q -n Alkalami -i org.sil.fonts source/*-Regular.ufo
